from Tkinter import *
import sqlite3
import tkMessageBox
con=sqlite3.Connection('SUPERKART.db')
cur=con.cursor()
cur.execute("create table if not exists data(name varchar(20) not null,address varchar(2) not null,password varchar(4) primary key)")
cur.execute("create table if not exists dataa(name varchar(20) not null,address varchar(2) not null,password varchar(4) primary key)")
con.commit()
def fun55():
        pas=StringVar()
        def fun66():
                pa=p.get()
                pp=str(pa)
                if pp!='':
                        root55.destroy()
                        root66=Tk()
                        root66.config(background='grey')
                        width = root66.winfo_screenwidth()
                        height = root66.winfo_screenheight()
                        root66.geometry('%sx%s' % (width, height))
                        root66.title('DETAILS')
                        Label(root66,text='',bg='grey').pack()
                        Label(root66,text='',bg='grey').pack()
                        Label(root66,text='DETAILS FOR PASSWORD:-',font='Arial 18 bold',bg='light blue').pack()
                        Label(root66,text='',bg='grey').pack()
                        Label(root66,text=pa,font='Arial 18 bold',bg='light blue').pack()
                        Label(root66,text='',bg='grey').pack()
                        Label(root66,text='~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',font='Arial 18 bold',bg='grey',fg='red').pack()
                        Label(root66,text='',bg='grey').pack()
                        cur=con.cursor()
                        cur.execute("select name from dataa where password==(?)",(pa,))        
                        aaa=cur.fetchall()
                        cur=con.cursor()
                        cur.execute("select address from dataa where password==(?)",(pa,))        
                        aaaa=cur.fetchall()
                        Label(root66,text='NAME:-',font='Arial 20 bold',bg='light blue',fg='red').pack()
                        Label(root66,text='',bg='grey').pack()
                        Label(root66,text=aaa[0],font='Arial 17 bold',bg='light green').pack()
                        Label(root66,text='',bg='grey').pack()
                        Label(root66,text='ADDRESS:-',font='Arial 17 bold',bg='light blue',fg='red').pack()
                        Label(root66,text='',bg='grey').pack()
                        Label(root66,text=aaaa[0],font='Arial 17 bold',bg='light green').pack()
                        con.commit()
                else:
                        root55.destroy()
                        tkMessageBox.showerror('ERROR','PASSWORD FIELD EMPTY')
                        fun55()
        root55=Tk()
        root55.config(background='light blue')
        width = root55.winfo_screenwidth()
        height = root55.winfo_screenheight()
        root55.geometry('%sx%s' % (width, height))
        root55.title("ORDER DETAILS")
        Label(root55,text='ORDER DETAILS',font='Arial 50 bold',bg='light green').pack()
        Label(root55,text='',bg='light blue').pack()
        Label(root55,text='',bg='light blue').pack()
        Label(root55,text='',bg='light blue').pack()
        Label(root55,text='ENTER YOUR PASSWORD',font='Arial 25 bold',bg='light blue').pack()
        Label(root55,text='',bg='light blue').pack()
        global p
        p=Entry(root55,show='*',font=large_font,bd=5)
        p.pack()
        Label(root55,text='',bg='light blue').pack()
        Button(root55,text='SHOW',command=fun66,font='Arial 12 bold').pack()
    

def fun1():
    #root.destroy()
    root1=Tk()
    width = root1.winfo_screenwidth()
    height = root1.winfo_screenheight()
    root1.geometry('%sx%s' % (width, height))
    root1.title('SUPER-KART')
    def fun2():
        global x1
        global x2
        global mi
        x1=PhotoImage(file='iphone.gif')
        x2=PhotoImage(file="watch.gif")
        mi=PhotoImage(file='a.gif')
        ak=tkMessageBox.askyesno('CHECK','PROCEED TO  PRODUCTS ?')
        if ak==False:
                root1.destroy()
        else:
                try:
                        cur=con.cursor()
                        cur.execute("insert into data values(?,?,?)",(name.get(),address.get(),passs.get()))
                        con.commit()
                        root2=Toplevel()
                        root2.config(background='light green')
                        width = root2.winfo_screenwidth()
                        height = root2.winfo_screenheight()
                        root2.geometry('%sx%s' % (width, height))
                        root2.title('PRODUCTS')
                        root2.minsize(width=766, height=566)
                        Label(root2,text='PRODUCTS',font=('arial',26,'bold'),bd=10,bg="light green",fg="black").pack()
                        Label(root2,text='',bg='light green').pack()
                        l1=Label(root2,image=x1)
                        l1.pack()
                        Label(root2,text='',bg='light green').pack()
                        def fun3():
                            def fun4():
                                def fun5():
                                    def fun6():
                                            global pa
                                            pa=p.get()
                                            if pa!='':
                                                    #root4.destroy()
                                                    root5.destroy()
                                                    root6=Tk()
                                                    root6.config(background='light blue')
                                                    width = root6.winfo_screenwidth()
                                                    height = root6.winfo_screenheight()
                                                    root6.geometry('%sx%s' % (width, height))
                                                    root6.title('DETAILS')
                                                    Label(root6,text='DETAILS FOR PASSWORD:-',font='Arial 18 bold',bg='light blue').pack()
                                                    Label(root6,text='',bg='light blue').pack()
                                                    Label(root6,text=pa,font='Arial 18 bold',bg='light blue').pack()
                                                    Label(root6,text='',bg='light blue').pack()
                                                    Label(root6,text='~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',font='Arial 18 bold',bg='light blue',fg='red').pack()
                                                    Label(root6,text='',bg='light blue').pack()
                                                    cur=con.cursor()
                                                    cur.execute("select name from dataa where password==(?)",(pa,))        
                                                    aaa=cur.fetchall()
                                                    cur=con.cursor()
                                                    cur.execute("select address from dataa where password==(?)",(pa,))        
                                                    aaaa=cur.fetchall()
                                                    Label(root6,text='NAME:-',font='Arial 20 bold',bg='light blue',fg='red').pack()
                                                    Label(root6,text='',bg='light blue').pack()
                                                    ##########################################################################################3
                                                    Label(root6,text=aaa[0],font='Arial 17 bold',bg='light green').pack()
                                                    ##############################################################################################
                                                    Label(root6,text='',bg='light blue').pack()
                                                    Label(root6,text='ADDRESS:-',font='Arial 17 bold',bg='light blue',fg='red').pack()
                                                    Label(root6,text='',bg='light blue').pack()
                                                    Label(root6,text=aaaa[0],font='Arial 17 bold',bg='light green').pack()
                                                    con.commit()
                                                    cur=con.cursor()
                                                    cur.execute("select name from dataa where password==(?)",(pa,))
                                                    aaa=cur.fetchall()
                                                    cur=con.cursor()
                                                    cur.execute("select address from dataa where password==(?)",(pa,))
                                                    aaaa=cur.fetchall()
                                                    con.commit()
                                            else:
                                                    #root4.destroy()
                                                    root5.destroy()
                                                    tkMessageBox.showerror('ERROR','PASSWORD FIELD EMPTY')
                                                    fun5() 
                                                                  
                                    root5=Tk()
                                    root5.config(background='light green')
                                    width = root5.winfo_screenwidth()
                                    height = root5.winfo_screenheight()
                                    root5.geometry('%sx%s' % (width, height))
                                    root5.title('ORDER DETAILS')
                                    #ffrffr
                                    #root5.title("ORDER DETAILS")
                                    Label(root5,text='ORDER DETAILS',font='Arial 50 bold',bg='light green').pack()
                                    Label(root5,text='',bg='light green').pack()
                                    Label(root5,text='',bg='light green').pack()
                                    Label(root5,text='',bg='light green').pack()
                                    Label(root5,text='ENTER YOUR PASSWORD',font='Arial 25 bold',bg='light blue').pack()
                                    Label(root5,text='',bg='light green').pack()
                                    global p
                                    p=Entry(root5,show='*',font=large_font,bd=5)
                                    p.pack()
                                    Label(root5,text='',bg='light green').pack()
                                    Button(root5,text='SHOW',command=fun6,font='Arial 10 bold').pack()
                                if cn.get()=='123456789' and cvv.get()=='123':
                                    root2.destroy()
                                    root3.destroy()
                                    root4=Tk()
                                    width = root4.winfo_screenwidth()
                                    height = root4.winfo_screenheight()
                                    root4.geometry('%sx%s' % (width, height))
                                    root4.config(background='light blue')
                                    #root4.minsize(width=766, height=566)
                                    Label(root4,text='',bg='light blue').pack()
                                    Label(root4,text='',bg='light blue').pack()
                                    Label(root4,text='',bg='light blue').pack()
                                    Label(root4,text='PAYMENT SUCESSFUL',font='Arial 15 bold',fg='green',bg='black').pack()
                                    Label(root4,text='',bg='light blue').pack()
                                    Label(root4,text='',bg='light blue').pack()
                                    Button(root4,text='ORDER DETAILS',command=fun5,font='Arial 13 bold').pack()
                                else:
                                    root2.destroy()
                                    root3.destroy()
                                    root44=Tk()
                                    root44.config(background='light blue')
                                    width = root44.winfo_screenwidth()
                                    height = root44.winfo_screenheight()
                                    root44.geometry('%sx%s' % (width, height))
                                    root44.title('TRY AGAIN!')
                                    root44.minsize(width=766, height=566)
                                    Label(root44,text='',bg='light blue').pack()
                                    Label(root44,text='',bg='light blue').pack()
                                    Label(root44,text='',bg='light blue').pack()
                                    Label(root44,text='PAYMENT UNSUCESSFUL',font='Arial 15 bold',fg='red',bg='black').pack()
                                    Label(root44,text='',bg='light blue').pack()
                                    Label(root44,text='',bg='light blue').pack()
                                    Button(root44,text='RE-PAY?',command=lambda:[root44.destroy(),fun3()],font='Arial 13 bold').pack()
                            i=tkMessageBox.askyesno('CONFIRM','RE-DIRECT TO PAYMENT GATEWAY ?')
                            if i==True:
                                    root3=Toplevel()
                                    root3.config(background='light green')
                                    width = root3.winfo_screenwidth()
                                    height = root3.winfo_screenheight()
                                    root3.geometry('%sx%s' % (width, height))
                                    root3.title("PAYMENT GATEWAY")
                                    Label(root3,text='PAYMENT GATEWAY',font='Arial 40 bold',bg='yellow').pack()
                                    Label(root3,text='',bg='light green').pack()
                                    Label(root3,text='',bg='light green').pack()
                                    Label(root3,text='',bg='light green').pack()
                                    Label(root3,text='ENTER CARD NUMBER',font='Arial 20 bold',bg='light blue').pack()
                                    Label(root3,text='',bg='light green').pack()
                                    cn=Entry(root3,font=large_font,bd=5)
                                    cn.pack()
                                    Label(root3,text='',bg='light green').pack()
                                    Label(root3,text='ENTER CVV',font='Arial 20 bold',bg='light blue').pack()
                                    Label(root3,text='',bg='light green').pack()
                                    cvv=Entry(root3,show='*',font=large_font,bd=5)
                                    cvv.pack()
                                    Label(root3,text='',bg='light green').pack()
                                    mo=Label(root3,image=mi)
                                    mo.pack()
                                    Label(root3,text='',bg='light green').pack()
                                    Button(root3,text='PAY',command=fun4,font='Arial 15 bold').pack()
                                    
                            elif i==False:
                                    ii=tkMessageBox.askyesno('ATTENTION','ABORT ?')
                                    if ii==True:
                                            root2.destroy()
                                            root1.destroy()
                            
                        Label(root2,text='IPHONE XS',font='Arial 12 bold').pack()
                        Label(root2,text='',bg='light green').pack()
                        Button(root2,text='Rs. 99,980',command=fun3,font='Arial 10 bold').pack()
                        Label(root2,text='',bg='light green').pack()
                        Label(root2,text='',bg='light green').pack()
                        l2=Label(root2,image=x2)
                        l2.pack()
                        Label(root2,text='',bg='light green').pack()
                        Label(root2,text='MENS WRIST WATCH',font='Arial 12 bold').pack()
                        Label(root2,text='',bg='light green').pack()
                        cur=con.cursor()
                        cur.execute("insert into dataa values(?,?,?)",(name.get(),address.get(),passs.get()))
                        con.commit()
                        Button(root2,text='Rs. 21,000',command=fun3,font='Arial 10 bold').pack()
                except:
                        tkMessageBox.showerror('ERROR!','PASSWORD ALREADY EXISTS!')
                        passs.delete(0,END)




    def check():
            if name.get()!='' and address.get()!='' and passs.get()!='':
                    fun2()
            else:
                    tkMessageBox.showerror('ERROR!','FIELDS MISSING! PLEASE FILL THEM')
                    root1.destroy()
                    fun1()


    root1.config(background='light blue')
    root1.title('SUPER-KART')
    global name
    global address
    global passs
    Label(root1,text='WELCOME TO SUPER-KART',font='Arial 50 bold',bg='yellow').pack()
    Label(root1,text='',bg='light blue').pack()
    Label(root1,text='       BUILT BY:-       ',font='Arial 18 bold',bg='gold').pack()
    Label(root1,text='KARTIK AGARWAL',font='Arial 18 bold',bg='gold').pack()
    Label(root1,text='         171B056         ',font='Arial 18 bold',bg='gold').pack()
    Label(root1,text='',bg='light blue').pack()
    Label(root1,text='OLD ORDER DETAILS',font='Arial 18 bold',bg='green').pack()
    Label(root1,text='',bg='light blue').pack()
    Button(root1,text='ORDER DETAILS',command=fun55,font='Arial 12 bold').pack()
    Label(root1,text='',bg='light blue').pack()
    Label(root1,text='---------------------------------------------------------------------------',bg='light blue').pack()
    Label(root1,text='NEW ORDER',font='Arial 18 bold',bg='green').pack()
    Label(root1,text='',bg='light blue').pack()
    Label(root1,text='ENTER YOUR FULL-NAME: ',font='Arial 14 bold',bg='light blue').pack()
    name=Entry(root1,font=large_font,bd=5)
    name.pack()
    Label(root1,text='',bg='light blue').pack()
    Label(root1,text='ENTER YOUR FULL ADDRESS: ',font='Arial 14 bold',bg='light blue').pack()
    address=Entry(root1,font=large_font,bd=5)
    address.pack()
    Label(root1,text='',bg='light blue').pack()
    Label(root1,text='SET YOUR PASSWORD: ',font='Arial 14 bold',bg='light blue').pack()
    passs=Entry(root1,show='*',font=large_font,bd=5)
    passs.pack()
    Label(root1,text='',bg='light blue').pack()
    Button(root1,text='ENTER',command=check,font='Arial 12 bold').pack()

def funn(e):
        root.destroy()
        fun1()


root=Tk()
root.config(background='purple')
large_font=('Arial',15)
root.title('WELCOME TO SUPER-KART')
width = root.winfo_screenwidth()
height = root.winfo_screenheight()
root.geometry('%sx%s' % (width, height))
Label(root,text='WELCOME TO SUPER-KART',font=('arial',35,'bold'),bd=10,bg="purple",fg="gold").pack()
Label(root,text='',bg='purple').pack()
imgg=PhotoImage(file='cover.gif')
ll=Label(root,image=imgg,bd=9,bg='gold')
ll.pack()
Label(root,text='',bg='purple',bd='10').pack()
Label(root,text='KARTIK AGARWAL',font=('arial',30,'bold'),bd=10,bg="purple",fg="gold").pack()
Label(root,text='',bg='purple').pack()
Label(root,text='ER NO.-171B056     ~       BATCH-BX(B2)',font=('arial',25,'bold'),bd=10,bg="purple",fg="gold").pack()
Label(root,text='',bg='purple').pack()
Label(root,text='EMAIL- kartikag1@yahoo.com',font=('arial',20,'bold'),bd=10,bg="purple",fg="gold").pack()
Label(root,text='',bg='purple').pack()
Label(root,text=' HOVER CURSOR ON PICTURE TO CONTINUE ',font=('arial',15,'bold'),bd=10,bg="purple",fg="CYAN").pack()
ll.bind('<Motion>',funn)
#root.after(3000,funn)
root.mainloop()
